version: '3.8'

services:
  oauthsrv:
    image: oauthsrv:0.1
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: testing
    volumes:
      - ./:/home/oauthsrv
    ports:
      - 8080:8080
    environment:
      PORT: 8080
