version: '3.8'

services:
  oauthsrv:
    image: oauthsrv:0.1
    build:
      context: .
      target: testing
    volumes:
      - ./:/home/oauthsrv
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGO_CONNSTR: 'mongodb://root:pass@mongo:27017'
      DB_NAME: 'oidc'

    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
      - ./initdb/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: oidc

volumes:
  mongo-data: {}
